name: fitness-application-melos

packages:
  - packages/flutter_no_internet_widget
  - packages/flutter_no_internet_widget/example

scripts:
  analyze:
    run: |
      melos exec -c 5 -- \
        dart analyze . --fatal-infos

  build-runner:
    description: Generate environment configuration, assets and other code generation
    packageFilters:
      flutter: true
      dirExists: lib
      scope: fitness_app
    run: melos exec dart run build_runner clean && melos exec dart run build_runner build -d

  locale-gen:
    description: Generate localization
    packageFilters:
      flutter: true
      dirExists: lib
      scope: fitness_app
    exec: dart run easy_localization:generate -f keys -o locale_keys.g.dart -O ./lib/gen -S assets/l10n

  build-apk:
    description: Generate localization
    packageFilters:
      flutter: true
      dirExists: lib
      scope: fitness_app
    exec: flutter build apk -t lib/main_development.dart
